### PR TITLE
Add terraform 0.11.2

### PR DESCRIPTION
**Pull request by so0k**
Add terraform 0.11.2 to docker image

```
Error: Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.2'.
```

### CODE REVIEW

**Comment by so0k** [comment]
Not sure if this is the only way to fix these version conflicts when someone within the team upgrades and modifies state outside of Atlantis without informing anyone.

This PR is to upstream [changes we had to roll out](https://github.com/honestbee/atlantis/commit/9d4470d5dcacf2765fa460158678bdf7246544bf) for our deployment (this is not urgent for us)

**Comment by FranOis** [comment]
I'd really like to see this merged if possible. Not sure I understand why circleci is exploding.

I'm currently setting up atlantis in our company but we are already running on 0.11.2 which prevents us from using Atlantis.

**Comment by so0k** [comment]
You can fork our custom Atlantis repo, it's easy to add more binaries to the docker image that way

**Comment by lkysow** [comment]
@FranOis sorry for the delay. TF is actually at 0.11.3 now so I've merged #240 instead.

If you'd like to manage your own versions then it's best to use a custom docker image as suggested by @so0k. You can build off of our image to make things easier, see https://github.com/hootsuite/atlantis#docker

**Comment by so0k** [comment]
I'd caution against adding secrets to images though. Use volumes for secrets, maybe the docs could be clarified

**Comment by lkysow** [comment]
Agreed, I will update the docs.

**Comment by lkysow** [comment]
@so0k, fixed in #242

**Pull request closed without merging**
